//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetChart
    {
        public int Id { get; set; }
        public int TargetId { get; set; }
        public string Name { get; set; }
        public int Sort { get; set; }
        public double Coeff { get; set; }
        public string Color { get; set; }
    
        public virtual Target Targets { get; set; }
    }
}
