//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public Target()
        {
            this.TargetCharts = new HashSet<TargetChart>();
        }
    
        public int Id { get; set; }
        public int Year { get; set; }
        public int Quarter { get; set; }
        public decimal Summ { get; set; }
        public double Month1Weight { get; set; }
        public double Month2Weight { get; set; }
        public double Month3Weight { get; set; }
        public string Color { get; set; }
        public string StartColor { get; set; }
    
        public virtual ICollection<TargetChart> TargetCharts { get; set; }
    }
}
